/* Generated by cbindgen from core/newt-ffi. Do not edit by hand. */

#ifndef NEWT_H
#define NEWT_H

/* This file is generated at build time; edits will be overwritten. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Version of the core, as a NUL-terminated static string.
 *
 * The returned pointer is valid for the lifetime of the process and must not
 * be freed by the caller.
 */
const char *newt_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NEWT_H */
