//! A session pairs one PTY and its child process with one [`Emulator`].
//!
//! Deliberately *not* using alacritty's `tty` or `event_loop` modules: owning
//! the PTY through `portable-pty` is what keeps the Windows port viable, since
//! that crate already absorbs the POSIX/ConPTY difference.

use std::io::{Read, Write};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};

use portable_pty::{native_pty_system, Child, CommandBuilder, MasterPty, PtySize};

use crate::emulator::{Emulator, SelectionMode, SizeInCells, DEFAULT_SCROLLBACK_LINES};
use crate::error::{Error, Result};
use crate::input::{encode_key, encode_mouse, encode_paste, encode_text, KeyEvent, MouseEvent};
use crate::metadata::SessionMetadata;

/// The PTY write end, shared with the reader thread so the terminal's replies
/// to queries can be sent without a round trip through the shell.
type SharedWriter = Arc<Mutex<Box<dyn Write + Send>>>;

/// Observer for raw PTY traffic, for debugging what a program actually sends.
///
/// Terminal bugs are usually invisible in the rendered grid — the interesting
/// evidence is the byte stream — so this seam is worth keeping permanently.
pub type Trace = Box<dyn FnMut(Direction, &[u8]) + Send>;

/// Shared so both the reader thread and the write path can log. Input covers
/// everything the child receives, whether typed by the user or generated by
/// the terminal answering a query; a trace that showed only one of those would
/// be actively misleading.
type SharedTrace = Arc<Mutex<Trace>>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    /// Bytes produced by the child process.
    Output,
    /// Bytes sent to the child, including the terminal's own query replies.
    Input,
}

/// Read buffer size. Large chunks on purpose — reading a byte at a time is the
/// classic way to make a terminal feel slow under heavy output.
const READ_BUFFER_BYTES: usize = 64 * 1024;

/// How a session should be started.
#[derive(Debug, Clone)]
pub struct SessionConfig {
    pub size: SizeInCells,
    /// Program to run. `None` uses the user's login shell.
    pub shell: Option<String>,
    /// Arguments for `shell`, excluding argv[0].
    ///
    /// A login shell takes none; running an agent CLI is the reason this
    /// exists — `claude --settings <path>` cannot be expressed without it.
    pub args: Vec<String>,
    /// Variables added to the inherited environment.
    ///
    /// Added, not replaced: `CommandBuilder::new` seeds itself from this
    /// process's environment, so a child still sees `PATH`, `HOME`, and the
    /// rest. Entries here override an inherited variable of the same name.
    pub env: Vec<(String, String)>,
    pub cwd: Option<PathBuf>,
    pub scrollback_lines: usize,
    /// Value advertised as `TERM`.
    pub term: String,
}

impl Default for SessionConfig {
    fn default() -> Self {
        Self {
            size: SizeInCells::new(80, 24),
            shell: None,
            args: Vec::new(),
            env: Vec::new(),
            cwd: None,
            scrollback_lines: DEFAULT_SCROLLBACK_LINES,
            term: "xterm-256color".to_string(),
        }
    }
}

/// A running terminal session.
///
/// Dropping it stops the child and joins the reader thread.
pub struct Session {
    emulator: Arc<Mutex<Emulator>>,
    master: Box<dyn MasterPty + Send>,
    writer: SharedWriter,
    child: Mutex<Box<dyn Child + Send + Sync>>,
    reader: Option<JoinHandle<()>>,
    child_exited: Arc<AtomicBool>,
    trace: Option<SharedTrace>,
    /// Bookkeeping for the UI. Not terminal state — nothing here is drawn.
    metadata: Mutex<SessionMetadata>,
}

impl Session {
    pub fn spawn(config: SessionConfig) -> Result<Self> {
        Self::spawn_with_trace(config, None)
    }

    /// Spawn with an observer on raw PTY traffic. See [`Trace`].
    pub fn spawn_with_trace(config: SessionConfig, trace: Option<Trace>) -> Result<Self> {
        let pty = native_pty_system();
        let pair = pty
            .openpty(pty_size(config.size))
            .map_err(|e| Error::Pty(format!("openpty failed: {e}")))?;

        let mut cmd = CommandBuilder::new(config.shell.clone().unwrap_or_else(default_shell));
        cmd.args(&config.args);
        cmd.env("TERM", &config.term);
        // After TERM, so a caller can deliberately override it.
        for (key, value) in &config.env {
            cmd.env(key, value);
        }
        if let Some(cwd) = &config.cwd {
            cmd.cwd(cwd);
        }

        let child = pair
            .slave
            .spawn_command(cmd)
            .map_err(|e| Error::Pty(format!("spawning the shell failed: {e}")))?;
        // The slave handle is not needed once the child holds it, and keeping it
        // open would stop the read side from ever seeing EOF.
        drop(pair.slave);

        let reader_handle = pair
            .master
            .try_clone_reader()
            .map_err(|e| Error::Pty(format!("cloning the pty reader failed: {e}")))?;
        let writer = pair
            .master
            .take_writer()
            .map_err(|e| Error::Pty(format!("taking the pty writer failed: {e}")))?;

        let emulator = Arc::new(Mutex::new(Emulator::new(
            config.size,
            config.scrollback_lines,
        )));
        let child_exited = Arc::new(AtomicBool::new(false));

        let writer: SharedWriter = Arc::new(Mutex::new(writer));
        let trace: Option<SharedTrace> = trace.map(|trace| Arc::new(Mutex::new(trace)));

        let reader = spawn_reader_thread(
            reader_handle,
            Arc::clone(&emulator),
            Arc::clone(&writer),
            Arc::clone(&child_exited),
            trace.clone(),
        );

        Ok(Self {
            emulator,
            master: pair.master,
            writer,
            child: Mutex::new(child),
            reader: Some(reader),
            child_exited,
            trace,
            metadata: Mutex::new(SessionMetadata::default()),
        })
    }

    /// Send input to the child process.
    pub fn write(&self, bytes: &[u8]) -> Result<()> {
        if let Some(trace) = &self.trace {
            if let Ok(mut trace) = trace.lock() {
                trace(Direction::Input, bytes);
            }
        }

        let mut writer = self.writer.lock().expect("writer mutex poisoned");
        writer.write_all(bytes)?;
        writer.flush()?;
        Ok(())
    }

    /// Encode a key press and send it to the child.
    ///
    /// Encoding depends on the terminal's current modes, so it is read and
    /// applied under one lock rather than sampled separately.
    pub fn send_key(&self, event: KeyEvent) -> Result<()> {
        let bytes = self.with_emulator(|emulator| {
            emulator.scroll_to_bottom();
            encode_key(event, emulator.modes())
        });
        if bytes.is_empty() {
            return Ok(());
        }
        self.write(&bytes)
    }

    /// Send text the platform produced directly, such as an IME commit.
    pub fn send_text(&self, text: &str) -> Result<()> {
        if text.is_empty() {
            return Ok(());
        }
        self.with_emulator(|emulator| emulator.scroll_to_bottom());
        self.write(&encode_text(text))
    }

    /// Send a mouse event, if the program asked to receive them.
    ///
    /// Returns whether anything was sent, so the caller can fall back to its
    /// own behavior — scrolling the viewport, for instance.
    pub fn send_mouse(&self, event: MouseEvent) -> Result<bool> {
        let bytes = self.with_emulator(|emulator| encode_mouse(event, emulator.modes()));
        match bytes {
            Some(bytes) if !bytes.is_empty() => {
                self.write(&bytes)?;
                Ok(true)
            }
            _ => Ok(false),
        }
    }

    /// Paste text, bracketed when the program has asked for it.
    pub fn send_paste(&self, text: &str) -> Result<()> {
        if text.is_empty() {
            return Ok(());
        }
        let bytes = self.with_emulator(|emulator| {
            emulator.scroll_to_bottom();
            encode_paste(text, emulator.modes())
        });
        self.write(&bytes)
    }

    // --- metadata ---

    /// A copy of this session's metadata.
    pub fn metadata(&self) -> SessionMetadata {
        self.metadata
            .lock()
            .expect("metadata mutex poisoned")
            .clone()
    }

    /// Replace this session's metadata.
    pub fn set_metadata(&self, metadata: SessionMetadata) {
        *self.metadata.lock().expect("metadata mutex poisoned") = metadata;
    }

    // --- selection and search ---

    pub fn start_selection(&self, col: u16, row: u16, side_right: bool, mode: SelectionMode) {
        self.with_emulator(|e| e.start_selection(col, row, side_right, mode));
    }

    pub fn update_selection(&self, col: u16, row: u16, side_right: bool) {
        self.with_emulator(|e| e.update_selection(col, row, side_right));
    }

    pub fn clear_selection(&self) {
        self.with_emulator(|e| e.clear_selection());
    }

    pub fn selected_text(&self) -> Option<String> {
        self.with_emulator(|e| e.selected_text())
    }

    /// Find `pattern`, selecting and scrolling to the match.
    pub fn find(&self, pattern: &str, forward: bool) -> bool {
        self.with_emulator(|e| e.find(pattern, forward))
    }

    /// Jump the viewport back to the live edge.
    pub fn scroll_to_bottom(&self) {
        self.with_emulator(|e| e.scroll_to_bottom());
    }

    /// Resize both the emulator and the PTY.
    ///
    /// Order matters: the child is told last, so by the time it redraws in
    /// response to SIGWINCH the grid is already the new shape.
    pub fn resize(&self, size: SizeInCells) -> Result<()> {
        self.with_emulator(|e| e.resize(size));
        self.master
            .resize(pty_size(size))
            .map_err(|e| Error::Pty(format!("resizing the pty failed: {e}")))
    }

    /// Run a closure against the emulator while holding its lock.
    pub fn with_emulator<T>(&self, f: impl FnOnce(&mut Emulator) -> T) -> T {
        let mut emulator = self.emulator.lock().expect("emulator mutex poisoned");
        f(&mut emulator)
    }

    /// Whether the child has closed the PTY.
    pub fn has_exited(&self) -> bool {
        self.child_exited.load(Ordering::Acquire)
    }

    /// Wait for the child to exit, returning its exit code.
    pub fn wait(&self) -> Result<u32> {
        let mut child = self.child.lock().expect("child mutex poisoned");
        child
            .wait()
            .map(|status| status.exit_code())
            .map_err(|e| Error::Pty(format!("waiting on the child failed: {e}")))
    }
}

impl Drop for Session {
    fn drop(&mut self) {
        // Kill first: the reader thread only unblocks once the child closes the
        // pty, so joining without this can hang on a shell that is still alive.
        if let Ok(mut child) = self.child.lock() {
            let _ = child.kill();
            let _ = child.wait();
        }
        if let Some(reader) = self.reader.take() {
            let _ = reader.join();
        }
    }
}

fn spawn_reader_thread(
    mut reader: Box<dyn Read + Send>,
    emulator: Arc<Mutex<Emulator>>,
    writer: SharedWriter,
    child_exited: Arc<AtomicBool>,
    trace: Option<SharedTrace>,
) -> JoinHandle<()> {
    thread::Builder::new()
        .name("newt-pty-reader".to_string())
        .spawn(move || {
            let mut buf = vec![0u8; READ_BUFFER_BYTES];
            loop {
                match reader.read(&mut buf) {
                    // EOF: the child closed the pty.
                    Ok(0) => break,
                    Ok(n) => {
                        if let Some(trace) = &trace {
                            if let Ok(mut trace) = trace.lock() {
                                trace(Direction::Output, &buf[..n]);
                            }
                        }

                        let replies = {
                            let mut emulator = match emulator.lock() {
                                Ok(guard) => guard,
                                // A panic elsewhere poisoned the lock; there is
                                // nothing useful this thread can do but stop.
                                Err(_) => break,
                            };
                            emulator.advance(&buf[..n]);
                            emulator.take_pty_output()
                        };

                        // Answer the child's questions immediately. Held past
                        // this point, a program waiting on a cursor-position
                        // report would hang.
                        if !replies.is_empty() {
                            if let Some(trace) = &trace {
                                if let Ok(mut trace) = trace.lock() {
                                    trace(Direction::Input, &replies);
                                }
                            }
                            if let Ok(mut writer) = writer.lock() {
                                if writer.write_all(&replies).is_err() {
                                    break;
                                }
                                let _ = writer.flush();
                            }
                        }
                    }
                    Err(e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
                    Err(_) => break,
                }
            }
            child_exited.store(true, Ordering::Release);
        })
        .expect("spawning the pty reader thread failed")
}

fn pty_size(size: SizeInCells) -> PtySize {
    PtySize {
        rows: size.rows,
        cols: size.cols,
        // Pixel dimensions are only consulted by programs drawing images; the
        // shell reports them, so leaving them zero is correct until we support
        // an image protocol.
        pixel_width: 0,
        pixel_height: 0,
    }
}

fn default_shell() -> String {
    std::env::var("SHELL").unwrap_or_else(|_| "/bin/sh".to_string())
}

#[cfg(test)]
mod tests {
    use std::time::{Duration, Instant};

    use super::*;

    /// Run a program to completion and return what it left on the screen.
    ///
    /// `/bin/sh` rather than the login shell: these assert what newt puts on
    /// the command line, and a test that inherits the running user's dotfiles
    /// is testing the dotfiles.
    fn screen_after(config: SessionConfig) -> String {
        let session = Session::spawn(config).expect("spawn");

        let deadline = Instant::now() + Duration::from_secs(5);
        while Instant::now() < deadline {
            let text = session.with_emulator(|emulator| emulator.visible_string());
            if !text.trim().is_empty() {
                return text;
            }
            std::thread::sleep(Duration::from_millis(20));
        }
        session.with_emulator(|emulator| emulator.visible_string())
    }

    #[test]
    fn arguments_and_environment_reach_the_child() {
        // Both in one program, because the failure this guards against is the
        // whole command line being dropped rather than one half of it: before
        // this, `spawn_with_trace` had no `.arg()` call at all.
        let screen = screen_after(SessionConfig {
            shell: Some("/bin/sh".to_string()),
            args: vec!["-c".to_string(), "printf %s \"$NEWT_TEST_VAR\"".to_string()],
            env: vec![("NEWT_TEST_VAR".to_string(), "reached".to_string())],
            ..SessionConfig::default()
        });

        assert!(screen.contains("reached"), "screen was {screen:?}");
    }

    #[test]
    fn the_child_still_inherits_the_environment_it_was_not_given() {
        // `CommandBuilder::new` seeds from this process's environment, so
        // adding a variable must not replace the rest. A child with no PATH or
        // HOME breaks in ways that look nothing like a terminal bug.
        let screen = screen_after(SessionConfig {
            shell: Some("/bin/sh".to_string()),
            args: vec!["-c".to_string(), "printf %s \"${HOME:-missing}\"".to_string()],
            env: vec![("NEWT_UNRELATED".to_string(), "1".to_string())],
            ..SessionConfig::default()
        });

        assert!(!screen.contains("missing"), "screen was {screen:?}");
    }

    #[test]
    fn explicit_environment_wins_over_the_default_term() {
        // TERM is set first so a caller can deliberately override it; pinning
        // the order here because reversing it would be invisible until some
        // program misdetected the terminal.
        let screen = screen_after(SessionConfig {
            shell: Some("/bin/sh".to_string()),
            args: vec!["-c".to_string(), "printf %s \"$TERM\"".to_string()],
            env: vec![("TERM".to_string(), "dumb".to_string())],
            ..SessionConfig::default()
        });

        assert!(screen.contains("dumb"), "screen was {screen:?}");
    }

    #[test]
    fn no_arguments_is_a_plain_shell() {
        let session = Session::spawn(SessionConfig {
            shell: Some("/bin/sh".to_string()),
            ..SessionConfig::default()
        })
        .expect("spawn");
        assert!(!session.has_exited());
    }
}
